version: "3"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    volumes:
      - ./configs/homepage:/app/config
      - ./configs/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 80:3000
    labels:
      homepage.group: Applications
      homepage.name: Gateway Dashboard
      homepage.icon: node-red.png
      homepage.href: :1880/ui/
      homepage.description: IoT Gateway Dashboard

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./configs/mosquitto:/mosquitto/config:ro
    ports:
      - 1883:1883
    labels:
      homepage.group: IoT Gateway Core
      homepage.name: Mosquitto
      homepage.icon: mqtt.png
      homepage.description: Local MQTT Broker
  
  telegraf:
    image: telegraf:alpine
    restart: always
    volumes:
      - ./configs/telegraf:/etc/telegraf:ro
    # environment:
    #   MQTT_USERNAME: ${MQTT_USERNAME:-unset}
    #   MQTT_PASSWORD: ${MQTT_PASSWORD:-unset}
    #   INFLUXDB_WRITE_TOKEN: ${INFLUXDB_WRITE_TOKEN}
    #   INFLUXDB_ORG: ${INFLUXDB_ORG}
    #   INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    labels:
      homepage.group: Services
      homepage.name: Telegraf
      homepage.icon: telegraf.png
      homepage.description: System Metrics to InfluxDB
  
  nodered:
    image: nodered/node-red:latest-minimal
    restart: always
    ports:
      - 1880:1880
    volumes:
      - nodered_data:/data
    environment:
      # - HOSTIP=${IOTGW_HOSTIP:-127.0.0.1}
      - TZ=${TIMEZONE}
    labels:
      # homepage setup
      homepage.group: Services
      homepage.name: Node-RED
      homepage.icon: node-red.png
      homepage.href: "${IOTGW_HOSTIP:-127.0.0.1}:1880"
      homepage.description: Node-RED

  influxdb:
    image: influxdb
    ports:
    - 8086:8086
    volumes:
    - influxdb:/var/lib/influxdb2
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=admin
    - DOCKER_INFLUXDB_INIT_PASSWORD=secret123
    - DOCKER_INFLUXDB_INIT_ORG=kpi-iot
    #- DOCKER_INFLUXDB_INIT_BUCKET=metrics
    labels:
      homepage.group: Services
      homepage.name: InfluxDB
      homepage.description: Time-Series Database.
      homepage.icon: influxdb.png
      homepage.href: http://localhost:8086

  grafana:
    image: grafana/grafana
    environment:
    - GF_SECURITY_ADMIN_USER=jacob
    - GF_SECURITY_ADMIN_PASSWORD=jacob
    volumes:
    - grafana:/var/lib/grafana
    labels:
      homepage.group: Applications
      homepage.name: Grafana
      homepage.href: http://${HOSTIP:-localhost}/grafana/
      homepage.description: Dashboards
      homepage.icon: grafana.png

volumes:
  nodered_data:
  grafana:
  influxdb: